In [38]:
from __future__ import print_function
import torch
# Tensorは
# construct a 5*3 matrix uninitailized
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00,  2.0000e+00,  7.4081e+12],
        [-3.6902e+19,  6.9793e+09,  4.5745e-41],
        [ 7.0020e+09,  4.5745e-41,  7.0021e+09],
        [ 4.5745e-41,  7.3873e+12,  4.2039e-45],
        [ 0.0000e+00,  0.0000e+00,  7.2064e+31]])


In [39]:
import torch
print(torch.__version__)

0.4.1


In [40]:
# construct a randomly initialized matrix
x = torch.rand(5, 3)
print(x)

tensor([[0.8514, 0.3009, 0.1380],
        [0.1686, 0.1581, 0.5513],
        [0.7374, 0.2504, 0.5180],
        [0.7721, 0.7323, 0.8665],
        [0.3939, 0.7681, 0.8751]])


In [41]:
#construct a matrix filled zeros and of dtype long
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [42]:
# construct a tensor directly from data
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [43]:
# create a tensor based on an exisiting tensor 
# These methods will reuse properties of the input tensor
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.5042, -0.5440,  0.5715],
        [ 1.4435,  1.2968,  2.9435],
        [-1.2213,  2.4615,  0.5594],
        [-0.7137, -0.6655,  1.7620],
        [-0.8360, -1.4677, -1.3614]])


In [44]:
# Get its size
print(x.size())

torch.Size([5, 3])


In [45]:
y = torch.rand(5, 3)
print(y)
print(x + y)

tensor([[0.4531, 0.3257, 0.9421],
        [0.3925, 0.4795, 0.3961],
        [0.2270, 0.4737, 0.5687],
        [0.5920, 0.1612, 0.5464],
        [0.1720, 0.7091, 0.9845]])
tensor([[-0.0511, -0.2183,  1.5136],
        [ 1.8360,  1.7763,  3.3395],
        [-0.9943,  2.9352,  1.1281],
        [-0.1217, -0.5044,  2.3085],
        [-0.6640, -0.7586, -0.3770]])


In [46]:
print(torch.add(x, y))

tensor([[-0.0511, -0.2183,  1.5136],
        [ 1.8360,  1.7763,  3.3395],
        [-0.9943,  2.9352,  1.1281],
        [-0.1217, -0.5044,  2.3085],
        [-0.6640, -0.7586, -0.3770]])


In [47]:
result = torch.empty(5, 3)
torch.add(x, y, out = result)
print(result)

tensor([[-0.0511, -0.2183,  1.5136],
        [ 1.8360,  1.7763,  3.3395],
        [-0.9943,  2.9352,  1.1281],
        [-0.1217, -0.5044,  2.3085],
        [-0.6640, -0.7586, -0.3770]])


In [48]:
y.add_(x)
print(y)

tensor([[-0.0511, -0.2183,  1.5136],
        [ 1.8360,  1.7763,  3.3395],
        [-0.9943,  2.9352,  1.1281],
        [-0.1217, -0.5044,  2.3085],
        [-0.6640, -0.7586, -0.3770]])


In [52]:
print(x)
print(x[:, 1])

tensor([[-0.5042, -0.5440,  0.5715],
        [ 1.4435,  1.2968,  2.9435],
        [-1.2213,  2.4615,  0.5594],
        [-0.7137, -0.6655,  1.7620],
        [-0.8360, -1.4677, -1.3614]])
tensor([-0.5440,  1.2968,  2.4615, -0.6655, -1.4677])


In [53]:
# resizing
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is inferred from otheer dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [58]:
# one element tensor is converted to python number by using .item()
x = torch.randn(1)
print(x.item())

1.1052515506744385


# Numpy Bridge

In [59]:
# converting a torch tensor to a numpy array
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [61]:
# the torch tensor and numpy array will share their underlying memory locations and changing one will change the another
a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [63]:
# converting numpy array to torch tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [64]:
# CUDA tensor
# let us run this cell only if CUDA is available
# we will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda") # a cuda device object
    y = torch.ones_like(x, device=device) # directly create a tensor on GPU
    x = x.to(device) # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu, torch.double")) # ``.to`` can also change dtype together!